### ISSUE TITLE
Option to persist toggled phantom spawning.

### ISSUE THREAD

**Issue by mibby** [Tallcraft/NerfPhantoms#10]
Would it be possible to add an option to persist phantom spawning for players on logout and across server restarts by writing players who toggle it on to a file and removing them from the file if they toggle it off again?

**Comment by Trikolon** [comment]
I have a WIP patch for this using redis as data storage. Might also add mySQL. I'm not a big fan of flatfile storage.

**Comment by jrarmstro** [comment]
Do you have a branch with this patch? How can we help?

**Comment by Trikolon** [comment]
Sorry for the delay, I finally found time to implement this. It's part of the 1.3.0 release.

https://github.com/Tallcraft/NerfPhantoms/releases/tag/v1.3.0
