### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by preludium975** [Tallcraft/NerfPhantoms#15]

**Comment by Trikolon** [comment]
Does the plugin not work for you on 1.17? If so please provide further details about exact server and plugin version along with any error messages you get in the console. 

I am running the plugin on a 1.17 server without any issues. 

Thank you!

**Comment by Trikolon** [comment]
Closing the issue since there has been no reply from the reporter and the plugin seems to work fine on 1.17.
