### ISSUE TITLE
Phantoms still spawning

### ISSUE THREAD

**Issue by Deiia** [Tallcraft/NerfPhantoms#17]
Hi! For some reason phantoms keep spawning for players even if they disabled them

**Comment by Trikolon** [comment]
Hi! Sorry for the delayed response. Could you post a copy of your `plugins/NerfPhantoms/config.yml` here? Please remove any sensitive data, such as passwords before posting.

**Comment by Trikolon** [comment]
Hi! Sorry for the delayed response. Could you post a copy of your `plugins/NerfPhantoms/config.yml` here? Please remove any sensitive data, such as passwords before posting.

**Comment by Trikolon** [comment]
No reply from reporter.
