### ISSUE TITLE
Feature request: Use a flat-file database or SQLite to persist player settings between server reboots by default

### ISSUE THREAD

**Issue by trwnh** [Tallcraft/NerfPhantoms#18]
### Steps to reproduce
1. Toggle phantom spawn for a player
2. Restart the server

### Expected behavior
Player phantom preferences are preserved (phantom spawns disabled if previously disabled)

### Actual behavior
Player phantom preferences are reset to default (phantom spawns enabled)

### Details

NerfPhantoms 1.3.0
Minecraft 1.18.2-paper-290

**Comment by Trikolon** [comment]
Thanks for the report!
Have you configured the database section in the config so the plugin can store player preferences in the database? Without a configured database there is no persistence.

**Comment by trwnh** [comment]
Changing the title of the issue. I can't really imagine a situation where having to set your preference every time the server reboots is a useful outcome
