### ISSUE TITLE
[Feature Request] Allow users to disable phantom-spawning for themselves

### ISSUE THREAD

**Issue by burdoto** [Tallcraft/NerfPhantoms#5]
I am recieving a lot of divided feedback about phantoms;
- One half of my server is asking me to disable phantoms
- The other half is asking me to keep them on

I was thinking about having the users themselves decide whether they want phantoms enabled or not, via a command, like /togglephantoms or such. Would it be possible for you to add such a command and feature to this plugin?

**Comment by Trikolon** [comment]
Thanks for your suggestion. That's a great idea! I'm quite busy with other projects currently but I'll check it out when I find the time.

**Comment by Trikolon** [comment]
Hi! Sorry, I didn't have time to look into this yet. You are very welcome to discuss implementation ideas here or submit a PR though!

**Comment by burdoto** [comment]
Don't feel bad! I currently dont have a need for this change that much anymore, so there is no reason to hurry.

**Comment by marvinej** [comment]
+1 to this. We would like it by a permission node to disable it for our staff @Trikolon

**Comment by Trikolon** [comment]
I've implemented this in https://github.com/Tallcraft/NerfPhantoms/commit/015831bdfcdcb5157cd9494bab0bd3b47dcd5afa
Also, there is a permission node to disable on login implemented here:
https://github.com/Tallcraft/NerfPhantoms/commit/672949a1fe99d56b8b1cf59fa4b726e3b99bb7f3

Currently testing it on my server.

**Comment by Trikolon** [comment]
Sorry for the delay on the release, I have just published `v1.2.0` which should be MC 1.15.1 compatible and includes the command + permission for disabling phantom spawn per player.
https://github.com/Tallcraft/NerfPhantoms/releases/tag/v1.2.0

**Comment by burdoto** [comment]
Sounds awesome, thanks for your work!
Do you think it would be possible for you to recompile this plugin into 1.13 Spigot API, defining API version in your `plugin.yml`? This way, your plugin will be compatible with Spigot 1.13, 1.14 and 1.15 versions. My server currently runs on 1.14.4 due to other plugin compatibility concerns, since most plugins don't seem to define an API version.

**Comment by Trikolon** [comment]
> This way, your plugin will be compatible with Spigot 1.13, 1.14 and 1.15 versions
Did you test on 1.14 and 1.13? It should still be compatible?
