### ISSUE TITLE
1.14 problems??

### ISSUE THREAD

**Issue by Altomun** [Tallcraft/NerfPhantoms#7]
We are running a 1.14 serverminer server and a number of things are not functioning. the /kill and /reload commands are indeed working, but nothing else is. we have tried to disable natural spawning and set their HP to 0, but they continue to spawn in our survival server. please help. #

**Comment by Trikolon** [comment]
Apologies for the delay! Could you please post your configuration here?
Please also include your server and plugin version.

**Comment by Altomun** [comment]
Sorry! We don't actually need assistance - we'd forgotten to change the
affected world. Thanks!!

**Comment by Trikolon** [comment]
Ok, great. Please let me know if you have any more issues.
